# Generated by Django 2.1.2 on 2018-10-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('organiser', models.CharField(default=0, max_length=200)),
                ('organizer_rollno', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('captain_name', models.CharField(max_length=200)),
                ('cap_rollno', models.CharField(max_length=200)),
                ('cap_contactno', models.IntegerField()),
                ('team_size', models.IntegerField(default=1)),
                ('sports', models.ManyToManyField(to='Add_on.Sport', verbose_name='list of sports played by this team')),
            ],
        ),
    ]
