# Generated by Django 2.1.2 on 2018-11-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='start of match')),
                ('end_time', models.DateTimeField(verbose_name='end of match')),
                ('result', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('organiser', models.CharField(default=0, max_length=200)),
                ('organizer_rollno', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('captain_name', models.CharField(max_length=200)),
                ('cap_rollno', models.CharField(max_length=200)),
                ('cap_contactno', models.IntegerField()),
                ('team_size', models.IntegerField(default=1)),
                ('sports', models.ManyToManyField(to='Add_on.Sport', verbose_name='list of sports played by this team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='Sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_on.Sport'),
        ),
        migrations.AddField(
            model_name='match',
            name='Team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='Add_on.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='Team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_on.Team'),
        ),
    ]
