# Generated by Django 2.1.2 on 2018-10-23 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Add_on', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='start of match')),
                ('end_time', models.DateTimeField(verbose_name='end of match')),
                ('result', models.CharField(max_length=200)),
                ('Sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_on.Sport')),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='Add_on.Team')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_on.Team')),
            ],
        ),
    ]
